from parser import (
    AST, Number, Variable, BinaryOp, VarDecl, Assignment, Print,
    If, While, Return, Call, Function, ArrayLiteral, ArrayIndex, Program
)


class LLVMCodeGenerator:
    """Generates LLVM IR from the AST."""

    def __init__(self):
        self.instructions = []
        self.current_function = None
        self.temp_counter = 0
        self.label_counter = 0
        self.variables = {}  # name -> (llvm_ptr_name, llvm_type)
        self.function_types = {}  # name -> (return_type, param_types)
        self.global_counter = 0
        self.string_literals = {}
        self.output_lines = []

    def generate(self, ast):
        """Generate LLVM IR from the AST."""
        print("   -> [Generator is preparing LLVM IR...]")

        # First pass: collect function signatures
        self._collect_function_signatures(ast)

        # Generate header
        self._emit_header()

        # Second pass: generate code
        self.visit(ast)

        # Generate footer (string literals)
        self._emit_footer()

        print(f"   -> [Generated {len(self.instructions)} LLVM instructions]")

    def _emit_header(self):
        """Emit LLVM module header."""
        self.output_lines.extend([
            "; C-Asterisk LLVM IR",
            "; Generated by c* compiler",
            "",
            "target triple = \"x86_64-pc-linux-gnu\"",
            "",
            "; External declarations",
            "declare i32 @printf(i8*, ...)",
            "",
        ])

    def _emit_footer(self):
        """Emit string literal definitions."""
        self.output_lines.append("")
        for string, name in self.string_literals.items():
            # Escape backslashes and quotes for LLVM IR
            llvm_string = string.replace('\\', '\\\\').replace('"', '\\"')
            # The string already contains the actual \n character, so we don't add extra \0A
            # But we need null terminator
            self.output_lines.append(f'{name} = private unnamed_addr constant [{len(string) + 1} x i8] c"{llvm_string}\\00"')

    def _collect_function_signatures(self, ast):
        """Collect function signatures for forward references."""
        if isinstance(ast, Program):
            for stmt in ast.statements:
                if isinstance(stmt, Function):
                    ret_type = self._llvm_type(stmt.return_type or "void")
                    self.function_types[stmt.name] = (ret_type, [])

    def _new_temp(self):
        """Generate a new temporary variable name."""
        self.temp_counter += 1
        return f"%{self.temp_counter}"

    def _new_label(self, prefix="L"):
        """Generate a new label name."""
        self.label_counter += 1
        return f"{prefix}{self.label_counter}"

    def _llvm_type(self, type_str):
        """Convert C-Asterisk type to LLVM type."""
        if type_str == "int" or type_str == "":
            return "i32"
        elif type_str == "float":
            return "float"
        elif type_str == "void":
            return "void"
        elif type_str.startswith("[") and type_str.endswith("]"):
            inner = self._llvm_type(type_str[1:-1])
            return f"[1024 x {inner}]"  # Fixed size arrays
        else:
            return "i32"

    def _emit(self, instruction, indent=True):
        """Emit an LLVM instruction."""
        if indent:
            self.instructions.append("    " + instruction)
        else:
            self.instructions.append(instruction)

    def visit(self, node):
        """Visit a node and generate code."""
        method_name = f"visit_{type(node).__name__}"
        method = getattr(self, method_name, self.generic_visit)
        return method(node)

    def generic_visit(self, node):
        """Default visitor."""
        if isinstance(node, AST):
            for attr_name, attr_value in node.__dict__.items():
                if isinstance(attr_value, AST):
                    self.visit(attr_value)
                elif isinstance(attr_value, list):
                    for item in attr_value:
                        if isinstance(item, AST):
                            self.visit(item)

    def visit_Program(self, node):
        """Generate code for a program."""
        # Separate functions from global statements
        functions = []
        global_stmts = []

        for stmt in node.statements:
            if isinstance(stmt, Function):
                functions.append(stmt)
            else:
                global_stmts.append(stmt)

        # Generate functions first
        for func in functions:
            self.visit(func)

        # Generate a main function for global statements
        if global_stmts:
            self._emit("define i32 @main() {", indent=False)
            self.variables = {}
            old_function = self.current_function
            self.current_function = Function("main", [], "int")

            for stmt in global_stmts:
                self.visit(stmt)

            # Return 0 from main
            self._emit("ret i32 0")
            self._emit("}")
            self._emit("")

            self.current_function = old_function

    def visit_Function(self, node):
        """Generate code for a function."""
        ret_type = self._llvm_type(node.return_type or "void")

        # Emit function header
        self._emit(f"define {ret_type} @{node.name}() {{", indent=False)

        # Reset state for function body
        self.variables = {}
        old_function = self.current_function
        self.current_function = node
        saved_instructions = self.instructions
        self.instructions = []

        # Generate body
        for stmt in node.body:
            self.visit(stmt)

        # Add implicit return for void functions
        if node.return_type == "void" or node.return_type is None:
            self._emit("ret void")

        self._emit("}")
        self._emit("")

        # Merge instructions
        func_instructions = self.instructions
        self.instructions = saved_instructions + func_instructions

        self.current_function = old_function

    def visit_VarDecl(self, node):
        """Generate code for a variable declaration."""
        # For array types, store as pointer
        if node.type_annotation.startswith("[") and node.type_annotation.endswith("]"):
            llvm_type = "i32*"
        else:
            llvm_type = self._llvm_type(node.type_annotation)

        # Allocate stack space
        var_ptr = self._new_temp()
        self._emit(f"{var_ptr} = alloca {llvm_type}")

        # Store initial value
        if isinstance(node.value, ArrayLiteral):
            # ArrayLiteral returns a pointer to the allocated array
            arr_ptr = self.visit(node.value)
            self._emit(f"store i32* {arr_ptr}, i32** {var_ptr}")
        else:
            value = self.visit(node.value)
            self._emit(f"store {llvm_type} {value}, {llvm_type}* {var_ptr}")

        self.variables[node.name] = (var_ptr, llvm_type)

    def visit_Assignment(self, node):
        """Generate code for an assignment."""
        if node.name not in self.variables:
            return

        var_ptr, llvm_type = self.variables[node.name]
        value = self.visit(node.value)
        self._emit(f"store {llvm_type} {value}, {llvm_type}* {var_ptr}")

    def visit_Print(self, node):
        """Generate code for a print statement."""
        value = self.visit(node.value)

        # Get or create format string for integers
        fmt_str = "%d\n"
        if fmt_str not in self.string_literals:
            self.string_literals[fmt_str] = f"@.str.{self.global_counter}"
            self.global_counter += 1
        fmt_name = self.string_literals[fmt_str]

        # Get pointer to format string
        fmt_ptr = self._new_temp()
        self._emit(f"{fmt_ptr} = getelementptr inbounds [4 x i8], [4 x i8]* {fmt_name}, i32 0, i32 0")

        # Call printf
        self._emit(f"call i32 (i8*, ...) @printf(i8* {fmt_ptr}, i32 {value})")

    def visit_If(self, node):
        """Generate code for an if statement."""
        else_label = self._new_label("else")
        end_label = self._new_label("endif")
        then_label = self._new_label("then")

        # Evaluate condition
        cond = self.visit(node.condition)

        if node.else_body:
            self._emit(f"br i1 {cond}, label %{then_label}, label %{else_label}")
            self._emit(f"{then_label}:")

            for stmt in node.body:
                self.visit(stmt)

            self._emit(f"br label %{end_label}")
            self._emit(f"{else_label}:")

            for stmt in node.else_body:
                self.visit(stmt)

            self._emit(f"br label %{end_label}")
        else:
            self._emit(f"br i1 {cond}, label %{then_label}, label %{end_label}")
            self._emit(f"{then_label}:")

            for stmt in node.body:
                self.visit(stmt)

            self._emit(f"br label %{end_label}")

        self._emit(f"{end_label}:")

    def visit_While(self, node):
        """Generate code for a while loop."""
        cond_label = self._new_label("while_cond")
        body_label = self._new_label("while_body")
        end_label = self._new_label("while_end")

        # Jump to condition check
        self._emit(f"br label %{cond_label}")

        # Condition block
        self._emit(f"{cond_label}:")
        cond = self.visit(node.condition)
        self._emit(f"br i1 {cond}, label %{body_label}, label %{end_label}")

        # Body block
        self._emit(f"{body_label}:")
        for stmt in node.body:
            self.visit(stmt)
        self._emit(f"br label %{cond_label}")

        # End block
        self._emit(f"{end_label}:")

    def visit_Return(self, node):
        """Generate code for a return statement."""
        value = self.visit(node.value)
        ret_type = self._llvm_type(self.current_function.return_type or "void")
        self._emit(f"ret {ret_type} {value}")

    def visit_Call(self, node):
        """Generate code for a function call."""
        func_name = node.name
        func_info = self.function_types.get(func_name)

        if func_info:
            ret_type, _ = func_info
        else:
            ret_type = "i32"

        # Generate argument values
        args = []
        for arg in node.args:
            arg_val = self.visit(arg)
            args.append(arg_val)

        args_str = ", ".join(args) if args else ""

        # Generate call
        if ret_type == "void":
            self._emit(f"call {ret_type} @{func_name}({args_str})")
            return "%undefined"
        else:
            result = self._new_temp()
            self._emit(f"{result} = call {ret_type} @{func_name}({args_str})")
            return result

    def visit_BinaryOp(self, node):
        """Generate code for a binary operation."""
        left = self.visit(node.left)
        right = self.visit(node.right)

        op = node.op.name
        result = self._new_temp()

        if op == "PLUS":
            self._emit(f"{result} = add i32 {left}, {right}")
        elif op == "MINUS":
            self._emit(f"{result} = sub i32 {left}, {right}")
        elif op == "MULTIPLY":
            self._emit(f"{result} = mul i32 {left}, {right}")
        elif op == "DIVIDE":
            self._emit(f"{result} = sdiv i32 {left}, {right}")
        elif op == "GREATER":
            cmp_result = self._new_temp()
            self._emit(f"{cmp_result} = icmp sgt i32 {left}, {right}")
            return cmp_result  # Return i1 directly
        elif op == "LESS":
            cmp_result = self._new_temp()
            self._emit(f"{cmp_result} = icmp slt i32 {left}, {right}")
            return cmp_result  # Return i1 directly
        else:
            result = left

        return result

    def visit_Number(self, node):
        """Generate code for a number literal."""
        return str(node.value)

    def visit_Variable(self, node):
        """Generate code for a variable reference."""
        if node.name not in self.variables:
            return "0"

        var_ptr, llvm_type = self.variables[node.name]
        result = self._new_temp()
        self._emit(f"{result} = load {llvm_type}, {llvm_type}* {var_ptr}")
        return result

    def visit_ArrayLiteral(self, node):
        """Generate code for an array literal."""
        elem_type = "i32"
        size = len(node.elements)

        # Allocate array on stack
        arr_ptr = self._new_temp()
        self._emit(f"{arr_ptr} = alloca [{size} x {elem_type}]")

        # Store each element
        for i, elem in enumerate(node.elements):
            elem_ptr = self._new_temp()
            self._emit(f"{elem_ptr} = getelementptr inbounds [{size} x {elem_type}], [{size} x {elem_type}]* {arr_ptr}, i32 0, i32 {i}")
            value = self.visit(elem)
            self._emit(f"store {elem_type} {value}, {elem_type}* {elem_ptr}")

        return arr_ptr

    def visit_ArrayIndex(self, node):
        """Generate code for array indexing."""
        if node.name not in self.variables:
            return "0"

        var_ptr, llvm_type = self.variables[node.name]
        index = self.visit(node.index)

        # Determine element type and actual array pointer
        elem_type = "i32"
        if llvm_type == "i32*":
            # Load the array pointer from the stored pointer
            arr_ptr = self._new_temp()
            self._emit(f"{arr_ptr} = load i32*, i32** {var_ptr}")
            llvm_type = "[1024 x i32]"  # Assume max size for loaded pointer
        elif llvm_type.startswith("["):
            parts = llvm_type.split(" x ")
            if len(parts) > 1:
                elem_type = parts[1].rstrip("]")
            arr_ptr = var_ptr
        else:
            arr_ptr = var_ptr

        # Get pointer to indexed element
        elem_ptr = self._new_temp()
        self._emit(f"{elem_ptr} = getelementptr inbounds {llvm_type}, {llvm_type}* {arr_ptr}, i32 0, i32 {index}")

        # Load the value
        result = self._new_temp()
        self._emit(f"{result} = load {elem_type}, {elem_type}* {elem_ptr}")
        return result

    def get_ir(self):
        """Get the generated LLVM IR as a string."""
        self.output_lines.extend(self.instructions)
        return "\n".join(self.output_lines)
